source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'json'
gem 'httparty'
gem 'unicorn'
gem 'rake'
gem 'simplecov', require: false, group: :test
gem 'minitest-reporters'
gem 'resque'
