name             'chef_client'
maintainer       'Gabriel Cardona'
maintainer_email 'gabr13l@bigearth.io'
license          'GPL v2'
description      'To bring up and configure an Ubuntu instance for use in the Big Earth ecosystem'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'ubuntu', '>= 14.04'
depends          'apt'
depends          'git'
depends          'users'
depends          'sudo'
depends          'oh-my-zsh'
# depends          'chef-server'
